### ISSUE TITLE
app deploy error OutOfMemoryError even after disabling cluster and messaging on wildfly 9

### ISSUE THREAD

**Issue by joyousjavadev** [openshift-cartridges/openshift-wildfly-cartridge#59]
When deploying my app on wildfly 9 cartridge I got OutOfMemoryError. I searched, and found an open issue and disabled the cluster and messaging from standalone.xml. I restarted the openshift app and tried to deploy my app again but still getting OutOfMemoryError  below.

[io.undertow.request] (default I/O-3) Undertow request failed HttpServerExchange{ GET /}: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at org.xnio.XnioWorker.execute(XnioWorker.java:741)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:212)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:227)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:128)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:143)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:90)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:49)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.NioTcpServerHandle.handleReady(NioTcpServerHandle.java:53)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:539)

**Comment by fjuma** [comment]
It's strange that an OutOfMemory issue is occurring even with clustering and messaging disabled. Are you able to provide the standalone.xml config file you used along with the server.log file?

**Comment by joyousjavadev** [comment]
Yes. Some details have been blacked out for obvious reason. Thank you.
https://gist.github.com/joyousjavadev/4259fbac8878d3280ce9

**Comment by fjuma** [comment]
Thanks. Please post the server.log file as well (once you ssh into your OpenShift instance, you can find it here: wildfly/logs/server.log).

Since you're using an additional PostgreSQL cartridge, did you happen to try creating a scalable application (rhc app create <WILDFLY_APP> -s jboss-wildfly-9)? This would install the PostgreSQL cartridge on a separate gear from WildFly and I'm wondering if that improves the OutOfMemory issue you're seeing.

**Comment by joyousjavadev** [comment]
server.log  https://gist.github.com/joyousjavadev/ba636cb06d32b4042f19
Yes, the -s option was used to create the app.

**Comment by fjuma** [comment]
From your server.log file, it doesn't look like your new config file was picked up since there are still references to jgroups even though that subsystem was supposed to be removed:

https://gist.github.com/joyousjavadev/ba636cb06d32b4042f19#file-server_blacked-log-L179-L192

Taking a closer look at your config file, there are also some changes needed to the ejb3 and infinispan subsystems to completely remove clustering.

I've created an updated version of the WildFly 9.0.1.Final standalone.xml without the jgroups and messaging subsystems and I've also made the necessary changes to the ejb3 and infinispan subsystems to remove clustering:

https://gist.github.com/fjuma/ce841b19a4bbea5af1aa

To try it out, add it to your application's git repo (in .openshift/config).

**Comment by joyousjavadev** [comment]
Thank you. That worked.

**Comment by fjuma** [comment]
Great!

**Comment by szzsa** [comment]
@fjuma Thank you! Great workaround.
